/**
 * Print file size statics as Markdown table.
 *
 * Usage:
 *  $ node ./scripts/compare-stat.mjs stat.json
 *  $ node ./scripts/compare-stat.mjs stat.json baseStat.json
 *
 * where .json files are generated by stat.mjs.
 * The latter (two arguments) invocation also prints the difference.
 */

import { readFileSync } from "node:fs";
import { parseArgs } from "node:util";

const { positionals } = parseArgs({
  args: process.args,
  allowPositionals: true,
});

if (!(1 <= positionals.length && positionals.length <= 2)) {
  console.error("Specify one or two JSON paths generated by stat.mjs");
  process.exit(0);
}

if (positionals.length === 1) {
  const [statPath] = positionals;
  // sizes: { path: string, size: number, gzipSize: number }[]
  const { hash, sizes } = JSON.parse(readFileSync(statPath, "utf-8"));

  console.log(`Commit: ${hash}`);
  console.log("");
  console.log("|path|size|gzip|");
  console.log("|:---|:---|:---|");
  for (const { path, size, gzipSize } of sizes) {
    console.log(`|\`${path}\`|${asKB(size)} (${size})|${asKB(gzipSize)} (${gzipSize})|`)
  }

} else {
  const [statPath, basePath] = positionals;
  // headSizes, baseSizes: { path: string, size: number, gzipSize: number }[]
  const { hash: headHash, sizes: headSizes } = JSON.parse(readFileSync(statPath, "utf-8"));
  const { hash: baseHash, sizes: baseSizes } = JSON.parse(readFileSync(basePath, "utf-8"));

  // table: { [path: string]: { path: string, baseSize: number, baseGzipSize: number, size: number, gzipSize: number } }
  const table = {};
  for (const { path, size, gzipSize } of headSizes)
    table[path] = { path, size, gzipSize, baseSize: 0, baseGzipSize: 0 };
  for (const { path, size, gzipSize } of baseSizes) {
    if (table[path]) {
      table[path].baseSize = size;
      table[path].baseGzipSize = gzipSize;
    } else {
      table[path] = { path, size: 0, gzipSize: 0, baseSize: size, baseGzipSize: gzipSize };
    }
  }

  console.log(`Commit: ${baseHash} => ${headHash}`);
  console.log("");
  console.log("|path|size|gzip|");
  console.log("|:---::---|:---|");
  for (const { path, baseSize, baseGzipSize, size, gzipSize } of Object.values(table)) {
    const sizeComp = `${asKB(size)} (${sign(size - baseSize)}B, ${percentDiff(size, baseSize)}%)`;
    const gzipSizeComp = `${asKB(gzipSize)} (${sign(gzipSize - baseGzipSize)}B, ${percentDiff(gzipSize, baseGzipSize)}%)`;
    console.log(`|\`${path}\`|${sizeComp}|${gzipSizeComp}|`);
  }
}

function asKB(n) {
  return `${(n / 1024).toFixed(2)} kB`;
}

function sign(n) {
  return ((n >= 0) ? "+" : "") + n;
}

function percentDiff(value, base) {
  return ((value >= base) ? "+" : "") + ((value - base) / base * 100).toFixed(2);
}
